version: "3"

services:
  server-app:
    container_name: server-app
    restart: always
    build: ./server-app
    ports:
      - "8000:8000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      MONGO_PASS: example
      MONGO_USER: root
      MONGO_DB: movies
      MONGO_PORT: 27017
      PORT: 8000

  client-app:
    container_name: client-app
    build: ./client-app
    ports:
      - "80:80"
    depends_on:
      - server-app
    environment:
      PORT: 3000

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: movies