FROM node:latest

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
ENV NODE_OPTIONS "--openssl-legacy-provider"
RUN yarn install --silent
RUN npm install react-scripts@3.0.1 -g --silent

# Copy app files
COPY . .

CMD ["npm", "run", "dev"]